"""Check that train.py satisfies the benchmark contract, using data/eval.csv as a stand-in for the hidden holdout.
Usage: python validate.py            (re-runs training; costs one experiment's worth of time but is NOT logged)
DO NOT EDIT THIS FILE.
"""
import json
import runpy
import sys
import time

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

task = json.load(open("task.json"))
t0 = time.time()
ns = runpy.run_path("train.py", run_name="__train__")
print(f"[validate] train.py ran in {time.time() - t0:.1f}s")
fn = ns.get("predict_proba")
if not callable(fn):
    sys.exit("[validate] FAIL: train.py does not define a callable predict_proba(df)")
df = pd.read_csv("data/eval.csv")
y = (df[task["target"]] == task["positive_label"]).astype(int).to_numpy()
p = np.asarray(fn(df.drop(columns=[task["target"]])), dtype=float).ravel()
if p.shape[0] != len(df):
    sys.exit(f"[validate] FAIL: predict_proba returned {p.shape[0]} values for {len(df)} rows")
if not np.all(np.isfinite(p)) or p.min() < 0 or p.max() > 1:
    sys.exit("[validate] FAIL: predict_proba must return finite probabilities in [0, 1]")
print(f"[validate] eval AUC via predict_proba (target column removed): {roc_auc_score(y, p):.4f}")
print("[validate] CONTRACT OK")
