#!/usr/bin/env bash
# Run the contract check with the benchmark's Python interpreter. Usage: ./validate.sh   (see validate.py)
# DO NOT EDIT THIS FILE.
set -u
cd "$(dirname "$0")"
[ -f ../bench.env ] && . ../bench.env
[ -f .bench/env ] && . ./.bench/env
export BENCH_THREADS="${BENCH_THREADS:-4}" OMP_NUM_THREADS="${BENCH_THREADS:-4}"
export BENCH_LEDGER_EXEMPT=1                          # recorded in the ledger as exempt, never refused
exec "${BENCH_PYTHON:-python}" validate.py
